### PR TITLE
History gaps

### LINKED ISSUE #2209: Your history - gap message error math
- [x] Math on gap error message looks to be not working (this example should be 2013-2014)

screen shot 2017-11-17 at 11 46 27 am

### PR DESCRIPTION
**Pull request by bmallred**
Resolves #2209 

 - Fix issue with dates not showing on gaps
 - Gaps adjusted to use old algorithm
 - Fix issue filling gaps
 - Added unit tests for finding gaps

### CODE REVIEW

File: src/components/Section/History/Employment/Employment.jsx [hunk 1]
```diff
@@ -76,21 +76,27 @@ export default class Employment extends SubsectionElement {
   }
 
   fillGap (dates) {
-    let items = [...this.props.value]
```
Comment (floresj) [inline src/components/Section/History/Employment/Employment.jsx]: Noice.

**Comment by floresj** [comment]
# Populate first pass
selection_603

# Gaps show up
selection_604

# Click to add gap
selection_605
