### PR TITLE
Submit print tweaks

### LINKED ISSUE #2127: Submit/Print tweaks
**Checking**:
- [x] Use "review-checking.svg" icon (in g drive svg icon folder)
- [x] Change p text to "Checking your form...

**Error:**
- [x] Change "List of incomplete sections" headline to a H3
- [x] Put p text below "Some required fields are incomplete" headline that reads "Please fix the errors listed below."
- [x] Use "review-error.svg" (in g drive svg icon folder)

**Complete:**
- [x] Change p text to read "Not a guarantee of acceptance, but all required fields are complete. Please sign the releases below and submit your form."

**Animations:**
- [x] Talk through animation ideas with Jay (verifying, icons, and release accordions)

**Print:**
- [x] Change header headline from "Submit" to "Print"

### PR DESCRIPTION
**Pull request by floresj**
Resolves #2127.

### CODE REVIEW

File: src/components/Section/Submission/Submission.jsx [hunk 1]
```diff
@@ -29,7 +28,7 @@ class Submission extends SectionElement {
   onSubmit () {
     // TODO: Generate has code here and send to print screen when
     // merged with persistence updates
-    this.props.dispatch(push('/form/submit/print'))
+    this.props.dispatch(push('/form/print'))
```
Comment (bmallred) [inline src/components/Section/Submission/Submission.jsx]: This will default to the `/intro` subsection

File: src/components/Section/Submission/Submission.jsx [hunk 2]
```diff
@@ -58,7 +57,7 @@ class Submission extends SectionElement {
     const sectionsStatus = statusForAllSections(this.props.Application)
     return (
       <SectionViews current={this.props.subsection} dispatch={this.props.dispatch}>
-        <SectionView name="">
+        <SectionView name="intro">
```
Comment (bmallred) [inline src/components/Section/Submission/Submission.jsx]: Blank subsections were removed a bit ago according to another issue so defaulting to `intro`

File: src/components/Section/Submission/Submission.jsx [hunk 3]
```diff
@@ -76,10 +75,6 @@ class Submission extends SectionElement {
             />
           </SubmissionStatus>
         </SectionView>
-        <SectionView name="print">
```
Comment (bmallred) [inline src/components/Section/Submission/Submission.jsx]: @floresj this was moved so the section header could change?

File: src/components/Section/Submission/Submission.jsx (hunk 2 above)
Comment (floresj) [reply src/components/Section/Submission/Submission.jsx]: :+1:  Thanks for the update !

File: src/components/Section/Submission/Submission.jsx (hunk 3 above)
Comment (floresj) [reply src/components/Section/Submission/Submission.jsx]: @bmallred Yesssir that is correct. I'm thinking in the persistence branch, we can either query from print page or pass the hash value via some router param.
